### ISSUE TITLE
re: solicitation for maintainers

### ISSUE THREAD

**Issue by mxndrwgrdnr** [holoviz/spatialpandas#38]
Responding per this [tweet](https://twitter.com/PhilippJFR/status/1282660862428356609), I'd be happy to contribute to this project. I'm a long-time user of scientific/geospatial Python stack, and have plenty of experience contributing to open source Python projects. I wouldn't call myself a Dask power user, but I'm familiar enough with the library to have bumped up against the limitations of the Dask + Geopandas workflow, which is why I'm eager to contribute to this effort. I'm not sure that Cython-oriented tasks are where I would be most effective from the start, as I don't have much development experience with Cython, but hopefully this can be a good excuse for me to gain some.

**Comment by jbednar** [comment]
Thanks for stepping up!  Spatialpandas is at the stage of a fully usable proof of concept, sufficient to illustrate how to do fast Numba-powered native-Python spatial data processing, but not yet fully fleshed out with a robust user community. We (the [HoloViz](https://holoviz.org) team) developed it to address limitations with the stack for rendering spatial data in [Datashader](https://datashader.org), but it deserves to have a much wider userbase and range of applications, far beyond just viz.

Spatialpandas gets its speed from [Numba](http://numba.pydata.org) rather than Cython, which in some ways lets you focus on Python syntax and concepts more than Cython does. In the best case, with Numba all you have to do is put `@jit` in front of your slow functions, though in practice getting good performance out of it typically takes understanding what Numba is doing at a deeper level, same as for Cython.

Probably the best way to get started is to look at the open issues here on this repo and see if any of what people have raised as issues are within your expertise.  If they are, jump right in!  If nothing jumps out at you or you want a bit more handholding, let me know and you can join our weekly HoloViz issue-triaging meetings where we try to stay on top of what users are reporting.

**Comment by mxndrwgrdnr** [comment]
Sounds good. Looks to me like most of the open issues should be covered by #37 apart from the .ipynb issue which sounds like a problem with either memory or the kubernetes config. I'll watch the repo for any new issues, but do feel free to tag me if something pops up that I miss. Don't think I can commit to a weekly meeting, but I'd be happy to sit in for one or two to help identify where work is needed.

**Comment by AndrewAnnex** [comment]
hey all, I've went ahead and contributed a recipe to the conda-forge for spatial pandas, anyone in this issue want to help maintain the feedstock? see #40

**Comment by AndrewAnnex** [comment]
@mxndrwgrdnr @jbednar interested in becoming maintainers for the conda forge feedstock as well? https://github.com/conda-forge/spatialpandas-feedstock

**Comment by jbednar** [comment]
I'm trying to avoid spreading me and my team too thin; we're focusing on viz and hoping this library will have a life outside of our viz tools. So I'm trying to stay back except for making sure it has a logo so that I can easily provide proper attribution for it in our docs and blogposts. That approach has worked out perfectly for [xarray-spatial](https://github.com/makepath/xarray-spatial), another viz-related but not viz-specific project that started as part of Datashader and has now gone on to an exciting new life beyond HoloViz. So I can be listed as a maintainer for the feedstock, but I'm really hoping someone more directly involved will step up for it!
