### ISSUE TITLE
SpatialPandas needs a logo

### ISSUE THREAD

**Issue by BoBednar** [holoviz/spatialpandas#39]
Looks like SpatialPandas needs a logo-- how about this one? It's based on the Pandas logo and it could go into the readme for instance. 

[SpatialPandasLogo.zip](https://github.com/holoviz/spatialpandas/files/4916218/SpatialPandasLogo.zip)

**Comment by jbednar** [comment]
Thanks! Here's a PNG version of that SVG: 
![image](https://user-images.githubusercontent.com/1695496/87381579-a38ee180-c55a-11ea-830e-b227eab33758.png)
@jorisvandenbossche or @TomAugspurger, is this distinct enough from the Pandas logo?  I think it should _resemble_ the Pandas one without being confusing with it.

**Comment by TomAugspurger** [comment]
Checking with the other pandas devs, but I don't think it'll be a problem. We don't have a formal process for handling things like this yet.

**Comment by jorisvandenbossche** [comment]
Ah, I was also just typing an answer ;) Here is it anyway

@jbednar I recently asked the same question for geopandas (yes, we still don't have a logo ..). Although you could maybe argue that the current proposal in geopandas has a higher level of resemblance (https://github.com/geopandas/geopandas/issues/1405)

The feedback from asking the pandas core team about this was:

- advice to use other color scheme
- need to check with NumFOCUS regarding the legal aspect -> their answer is that this is OK if the pandas team publicly gives permission

**Comment by jbednar** [comment]
Hmm; I just noticed that Bo's logo actually forms a 'G', in addition to the obvious white 'p' and 'd'; maybe it's a contender for a GeoPandas logo instead of for SpatialPandas? :-)  E.g. with geo-related colors:

![image](https://user-images.githubusercontent.com/1695496/87446468-f26e6280-c5be-11ea-941f-cedd55e1a4dc.png)

**Comment by jorisvandenbossche** [comment]
To be honest, my first reaction was (but I didn't want to state it at first ;)): "nice, can we pick it for GeoPandas?"

**Comment by BoBednar** [comment]
@jorisvandenbossche I'd love for this to be used for GeoPandas! You're welcome to either variation, I'll find something else that could work for SpatialPandas.

**Comment by mxndrwgrdnr** [comment]
I know I'm new here, but if you flip the pandas logo by 45 degrees, there is an S-for-spatial to be found:
![Artboard 1](https://user-images.githubusercontent.com/1395651/87461101-c654e080-c5c2-11ea-8faa-752a11764302.png)

**Comment by jbednar** [comment]
@mxndrwgrdnr, that looks cool!  Let's postpone deciding this for a bit while GeoPandas works out which one they want to use, and come back to this.

@jorisvandenbossche, here's PNG and SVG source for the geo-colored version:
[possiblegeopandaslogo.zip](https://github.com/holoviz/spatialpandas/files/4921568/possiblegeopandaslogo.zip)

**Comment by jbednar** [comment]
It sounds like (a) GeoPandas may go with a variant of the one from this issue, and (b) they won't decide for some time, so we should probably go ahead with another one. @mxndrwgrdnr, here's one inspired by your observation combined with Bo's original:

![spatialpandaslogo](https://user-images.githubusercontent.com/1695496/87601596-039c9980-c6bb-11ea-86dc-997d8305cdd1.png)

@TomAugspurger and @jorisvandenbossche , I used colors from the pandas color scheme because this logo is even further from the graphical shape of the pandas logo. Keeping similar colors helps there be _some_ clear visible relationship, plus this library is not specifically geo so there's no particular color scheme it should use otherwise.  Please let me know if the Pandas team objects!

**Comment by brl0** [comment]
I like it... the 'S' in the logo looks like a fragment of a space filling curve, which is really on point given how spatialpandas works.

**Comment by ppwadhwa** [comment]
I like it too!

**Comment by TomAugspurger** [comment]
Checking with the other pandas devs. I'll give it a week or so to see if there are any objections.

**Comment by jbednar** [comment]
Thanks, @TomAugspurger; let us know!  

@brl0 , that's a great observation; people on this thread have been so much smarter at me at noticing such things!  Yes, it's highly reminiscent of the Hilbert space-filling curve SpatialPandas uses for spatial partitioning:

![image](https://user-images.githubusercontent.com/1695496/87697450-b6223a00-c757-11ea-95ba-5429e549578f.png)

Bo pointed out that the version above has an unfortunate resemblance to a swastika, which I now can't unsee.  Here's a version to address that, though it's become even further from the pandas logo shape:

![spatialpandaslogo_dot](https://user-images.githubusercontent.com/1695496/87696905-18c70600-c757-11ea-9098-d2cbdce91cc8.png)

**Comment by mxndrwgrdnr** [comment]
I'm happy to be the token bar mitzvah boy who declares the first logo to be far-removed enough from a swastika, but also happy to keep iterating. I like your second version a lot as well, @jbednar.

**Comment by jbednar** [comment]
@TomAugspurger , it's been a week, so we'll go with the last version (dots, no swastika motifs) unless there's any final Pandas-dev objection today.  Thanks, everyone!

**Comment by TomAugspurger** [comment]
Sounds good, thanks.

**Comment by jbednar** [comment]
Ok, it's live:

![image](https://user-images.githubusercontent.com/1695496/88587017-e3ee6500-d01a-11ea-8f6f-1e7b3b05bc83.png)
